version: 2.1
jobs:
  build-a:
    docker:
      - image: denoland/deno:1.43.6
    steps:
      - checkout
      - run: |
          echo foo > foo.txt

workflows:
  example-workflow:
    jobs:
      - build-a
