version: 2.1

executors:
  deno-executor:
    docker:
      - image: denoland/deno:1.43.6
jobs:
  build-a:
    executor: deno-executor
    steps:
      - checkout
      - run:
          name: "Create sample data"
          command: |
            mkdir -p tmp/data
            echo message from build-a | tee tmp/data/output.txt
      - run:
          name: "List contents of tmp dir"
          command: |
            ls -lR
      - persist_to_workspace:
          root: tmp
          paths:
            - data
  build-b:
    executor: deno-executor
    steps:
      - attach_workspace:
          name: "Attach workspace"
          at: tmp
      - run:
          name: "restore workspace data"
          command: |
            ls -lR .
      - run:
          name: "check workspace data"
          command: cat tmp/data/output.txt

workflows:
  example-workflow:
    jobs:
      - build-a
      - build-b:
          requires:
            - build-a

